[book]
authors = ["Axo Developer Co"]
language = "en"
multilingual = false
src = "src"
title = "dist"

[output.html]
git-repository-url = "https://github.com/axodotdev/cargo-dist"
edit-url-template = "https://github.com/axodotdev/cargo-dist/edit/main/book/{path}"
search.use-boolean-and = true

[output.linkcheck]
warning-policy = "error"

[output.html.redirect]
"/ci/github.html" = "./index.html"
"/generic-builds.html" = "./custom-builds.html"
"/way-too-quickstart.html" = "./quickstart/index.html"

[preprocessor.toc]
command = "mdbook-toc"
